### ISSUE TITLE
Update .github/workflows/main.yml

### ISSUE THREAD

**Issue by sparkcity** [Astrotech89/ME5e-FoundryVTT#10]
```
on:
  push:
    branches:
      - master
```
- master needs to be replaced with main
- Recommend doing this when this module is ready to be released and replace the old one. Once updated, every time we push to main a new release will be automatically generated with the updated version number.
